# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "freyja-template-app"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
# These two dependencies are required for anyone implementing a Freyja application
freyja = { git = "https://github.com/eclipse-ibeji/freyja", branch = "wilyle/test-freyja-lib" }
tokio = { version = "1.0", features = ["macros"] }

# Put any dependencies that you need for your adapters down here.
my-adapters = { git = "https://github.com/my-org/my-repo" }